[workspace]
members = [
    "xpath",
    "xpath_unit_tests",
    "test_packages/xpath_test_fnabs",
    "test_packages/xpath_test_fnadjust_date_to_timezone",
    "test_packages/xpath_test_fnadjust_datetime_to_timezone",
    "test_packages/xpath_test_fnadjust_time_to_timezone",
    "test_packages/xpath_test_fnanalyze_string",
    "test_packages/xpath_test_fnapply",
    "test_packages/xpath_test_fnavailable_environment_variables",
    "test_packages/xpath_test_fnavg",
    "test_packages/xpath_test_fnbase_uri",
    "test_packages/xpath_test_fnboolean",
    "test_packages/xpath_test_fnceiling",
    "test_packages/xpath_test_fncodepoint_equal",
    "test_packages/xpath_test_fncodepoints_to_string",
    "test_packages/xpath_test_fncollation_key",
    "test_packages/xpath_test_fncollection",
    "test_packages/xpath_test_fncompare",
    "test_packages/xpath_test_fnconcat",
    "test_packages/xpath_test_fncontains",
    "test_packages/xpath_test_fncontains_token",
    "test_packages/xpath_test_fncount",
    "test_packages/xpath_test_fncurrent_date",
    "test_packages/xpath_test_fncurrent_datetime",
    "test_packages/xpath_test_fncurrent_time",
    "test_packages/xpath_test_fndata",
    "test_packages/xpath_test_fndatetime",
    "test_packages/xpath_test_fnday_from_date",
    "test_packages/xpath_test_fnday_from_datetime",
    "test_packages/xpath_test_fndays_from_duration",
    "test_packages/xpath_test_fndeep_equal",
    "test_packages/xpath_test_fndefault_collation",
    "test_packages/xpath_test_fndefault_language",
    "test_packages/xpath_test_fndistinct_values",
    "test_packages/xpath_test_fndoc",
    "test_packages/xpath_test_fndoc_available",
    "test_packages/xpath_test_fndocument_uri",
    "test_packages/xpath_test_fnelement_with_id",
    "test_packages/xpath_test_fnempty",
    "test_packages/xpath_test_fnencode_for_uri",
    "test_packages/xpath_test_fnends_with",
    "test_packages/xpath_test_fnenvironment_variable",
    "test_packages/xpath_test_fnerror",
    "test_packages/xpath_test_fnescape_html_uri",
    "test_packages/xpath_test_fnexactly_one",
    "test_packages/xpath_test_fnexists",
    "test_packages/xpath_test_fnfalse",
    "test_packages/xpath_test_fnfilter",
    "test_packages/xpath_test_fnfloor",
    "test_packages/xpath_test_fnfold_left",
    "test_packages/xpath_test_fnfold_right",
    "test_packages/xpath_test_fnfor_each",
    "test_packages/xpath_test_fnfor_each_pair",
    "test_packages/xpath_test_fnformat_date",
    "test_packages/xpath_test_fnformat_datetime",
    "test_packages/xpath_test_fnformat_integer",
    "test_packages/xpath_test_fnformat_number",
    "test_packages/xpath_test_fnformat_time",
    "test_packages/xpath_test_fnfunction_arity",
    "test_packages/xpath_test_fnfunction_lookup",
    "test_packages/xpath_test_fnfunction_name",
    "test_packages/xpath_test_fngenerate_id",
    "test_packages/xpath_test_fnhas_children",
    "test_packages/xpath_test_fnhead",
    "test_packages/xpath_test_fnhours_from_datetime",
    "test_packages/xpath_test_fnhours_from_duration",
    "test_packages/xpath_test_fnhours_from_time",
    "test_packages/xpath_test_fnid",
    "test_packages/xpath_test_fnidref",
    "test_packages/xpath_test_fnimplicit_timezone",
    "test_packages/xpath_test_fnin_scope_prefixes",
    "test_packages/xpath_test_fnindex_of",
    "test_packages/xpath_test_fninnermost",
    "test_packages/xpath_test_fninsert_before",
    "test_packages/xpath_test_fniri_to_uri",
    "test_packages/xpath_test_fnjson_doc",
    "test_packages/xpath_test_fnjson_to_xml",
    "test_packages/xpath_test_fnlang",
    "test_packages/xpath_test_fnlast",
    "test_packages/xpath_test_fnload_xquery_module",
    "test_packages/xpath_test_fnlocal_name",
    "test_packages/xpath_test_fnlocal_name_from_qname",
    "test_packages/xpath_test_fnlower_case",
    "test_packages/xpath_test_fnmatches",
    "test_packages/xpath_test_fnmatches_re",
    "test_packages/xpath_test_fnmax",
    "test_packages/xpath_test_fnmin",
    "test_packages/xpath_test_fnminutes_from_datetime",
    "test_packages/xpath_test_fnminutes_from_duration",
    "test_packages/xpath_test_fnminutes_from_time",
    "test_packages/xpath_test_fnmonth_from_date",
    "test_packages/xpath_test_fnmonth_from_datetime",
    "test_packages/xpath_test_fnname",
    "test_packages/xpath_test_fnnamespace_uri",
    "test_packages/xpath_test_fnnamespace_uri_for_prefix",
    "test_packages/xpath_test_fnnamespace_uri_from_qname",
    "test_packages/xpath_test_fnnilled",
    "test_packages/xpath_test_fnnode_name",
    "test_packages/xpath_test_fnnormalize_space",
    "test_packages/xpath_test_fnnormalize_unicode",
    "test_packages/xpath_test_fnnot",
    "test_packages/xpath_test_fnnumber",
    "test_packages/xpath_test_fnone_or_more",
    "test_packages/xpath_test_fnoutermost",
    "test_packages/xpath_test_fnparse_ietf_date",
    "test_packages/xpath_test_fnparse_json",
    "test_packages/xpath_test_fnparse_xml",
    "test_packages/xpath_test_fnparse_xml_fragment",
    "test_packages/xpath_test_fnpath",
    "test_packages/xpath_test_fnposition",
    "test_packages/xpath_test_fnprefix_from_qname",
    "test_packages/xpath_test_fnqname",
    "test_packages/xpath_test_fnrandom_number_generator",
    "test_packages/xpath_test_fnremove",
    "test_packages/xpath_test_fnreplace",
    "test_packages/xpath_test_fnresolve_qname",
    "test_packages/xpath_test_fnresolve_uri",
    "test_packages/xpath_test_fnreverse",
    "test_packages/xpath_test_fnroot",
    "test_packages/xpath_test_fnround",
    "test_packages/xpath_test_fnround_half_to_even",
    "test_packages/xpath_test_fnseconds_from_datetime",
    "test_packages/xpath_test_fnseconds_from_duration",
    "test_packages/xpath_test_fnseconds_from_time",
    "test_packages/xpath_test_fnserialize",
    "test_packages/xpath_test_fnsort",
    "test_packages/xpath_test_fnstarts_with",
    "test_packages/xpath_test_fnstatic_base_uri",
    "test_packages/xpath_test_fnstring",
    "test_packages/xpath_test_fnstring_join",
    "test_packages/xpath_test_fnstring_length",
    "test_packages/xpath_test_fnstring_to_codepoints",
    "test_packages/xpath_test_fnsubsequence",
    "test_packages/xpath_test_fnsubstring",
    "test_packages/xpath_test_fnsubstring_after",
    "test_packages/xpath_test_fnsubstring_before",
    "test_packages/xpath_test_fnsum",
    "test_packages/xpath_test_fntail",
    "test_packages/xpath_test_fntimezone_from_date",
    "test_packages/xpath_test_fntimezone_from_datetime",
    "test_packages/xpath_test_fntimezone_from_time",
    "test_packages/xpath_test_fntokenize",
    "test_packages/xpath_test_fntrace",
    "test_packages/xpath_test_fntransform",
    "test_packages/xpath_test_fntranslate",
    "test_packages/xpath_test_fntrue",
    "test_packages/xpath_test_fnunordered",
    "test_packages/xpath_test_fnunparsed_text",
    "test_packages/xpath_test_fnunparsed_text_available",
    "test_packages/xpath_test_fnunparsed_text_lines",
    "test_packages/xpath_test_fnupper_case",
    "test_packages/xpath_test_fnxml_to_json",
    "test_packages/xpath_test_fnyear_from_date",
    "test_packages/xpath_test_fnyear_from_datetime",
    "test_packages/xpath_test_fnzero_or_one",
    "test_packages/xpath_test_opadd_daytimeduration_to_date",
    "test_packages/xpath_test_opadd_daytimeduration_to_datetime",
    "test_packages/xpath_test_opadd_daytimeduration_to_time",
    "test_packages/xpath_test_opadd_daytimedurations",
    "test_packages/xpath_test_opadd_yearmonthduration_to_date",
    "test_packages/xpath_test_opadd_yearmonthduration_to_datetime",
    "test_packages/xpath_test_opadd_yearmonthdurations",
    "test_packages/xpath_test_opanyuri_equal",
    "test_packages/xpath_test_opanyuri_greater_than",
    "test_packages/xpath_test_opanyuri_less_than",
    "test_packages/xpath_test_opbang",
    "test_packages/xpath_test_opbase64binary_equal",
    "test_packages/xpath_test_opbase64binary_greater_than",
    "test_packages/xpath_test_opbase64binary_less_than",
    "test_packages/xpath_test_opboolean_equal",
    "test_packages/xpath_test_opboolean_greater_than",
    "test_packages/xpath_test_opboolean_less_than",
    "test_packages/xpath_test_opconcat",
    "test_packages/xpath_test_opconcatenate",
    "test_packages/xpath_test_opdate_equal",
    "test_packages/xpath_test_opdate_greater_than",
    "test_packages/xpath_test_opdate_less_than",
    "test_packages/xpath_test_opdatetime_equal",
    "test_packages/xpath_test_opdatetime_greater_than",
    "test_packages/xpath_test_opdatetime_less_than",
    "test_packages/xpath_test_opdaytimeduration_greater_than",
    "test_packages/xpath_test_opdaytimeduration_less_than",
    "test_packages/xpath_test_opdivide_daytimeduration",
    "test_packages/xpath_test_opdivide_daytimeduration_by_daytimeduration",
    "test_packages/xpath_test_opdivide_yearmonthduration",
    "test_packages/xpath_test_opdivide_yearmonthduration_by_yearmonthduration",
    "test_packages/xpath_test_opduration_equal",
    "test_packages/xpath_test_opexcept",
    "test_packages/xpath_test_opgday_equal",
    "test_packages/xpath_test_opgmonth_equal",
    "test_packages/xpath_test_opgmonthday_equal",
    "test_packages/xpath_test_opgyear_equal",
    "test_packages/xpath_test_opgyearmonth_equal",
    "test_packages/xpath_test_ophexbinary_equal",
    "test_packages/xpath_test_ophexbinary_greater_than",
    "test_packages/xpath_test_ophexbinary_less_than",
    "test_packages/xpath_test_opintersect",
    "test_packages/xpath_test_opis_same_node",
    "test_packages/xpath_test_opmultiply_daytimeduration",
    "test_packages/xpath_test_opmultiply_yearmonthduration",
    "test_packages/xpath_test_opnode_after",
    "test_packages/xpath_test_opnode_before",
    "test_packages/xpath_test_opnotation_equal",
    "test_packages/xpath_test_opnumeric_add",
    "test_packages/xpath_test_opnumeric_divide",
    "test_packages/xpath_test_opnumeric_equal",
    "test_packages/xpath_test_opnumeric_greater_than",
    "test_packages/xpath_test_opnumeric_integer_divide",
    "test_packages/xpath_test_opnumeric_less_than",
    "test_packages/xpath_test_opnumeric_mod",
    "test_packages/xpath_test_opnumeric_multiply",
    "test_packages/xpath_test_opnumeric_subtract",
    "test_packages/xpath_test_opnumeric_unary_minus",
    "test_packages/xpath_test_opnumeric_unary_plus",
    "test_packages/xpath_test_opqname_equal",
    "test_packages/xpath_test_opsame_key",
    "test_packages/xpath_test_opstring_equal",
    "test_packages/xpath_test_opstring_greater_than",
    "test_packages/xpath_test_opstring_less_than",
    "test_packages/xpath_test_opsubtract_dates",
    "test_packages/xpath_test_opsubtract_datetimes",
    "test_packages/xpath_test_opsubtract_daytimeduration_from_date",
    "test_packages/xpath_test_opsubtract_daytimeduration_from_datetime",
    "test_packages/xpath_test_opsubtract_daytimeduration_from_time",
    "test_packages/xpath_test_opsubtract_daytimedurations",
    "test_packages/xpath_test_opsubtract_times",
    "test_packages/xpath_test_opsubtract_yearmonthduration_from_date",
    "test_packages/xpath_test_opsubtract_yearmonthduration_from_datetime",
    "test_packages/xpath_test_opsubtract_yearmonthdurations",
    "test_packages/xpath_test_optime_equal",
    "test_packages/xpath_test_optime_greater_than",
    "test_packages/xpath_test_optime_less_than",
    "test_packages/xpath_test_opto",
    "test_packages/xpath_test_opunion",
    "test_packages/xpath_test_opyearmonthduration_greater_than",
    "test_packages/xpath_test_opyearmonthduration_less_than",
    "test_packages/xpath_test_xsdouble_from_int",
    "test_packages/xpath_test_xsfloat_from_double",
    "test_packages/xpath_test_xsfloat_from_int",
    "test_packages/xpath_test_xsinteger_from_double",
    "test_packages/xpath_test_xsinteger_from_float",
]
